# Generated by Django 3.1.7 on 2021-03-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created',)},
        ),
    ]
