# Generated by Django 3.1.7 on 2021-04-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210331_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created', '-price')},
        ),
    ]
